In [1]:
## NEURAL NETWORK USING NUMPY
import sys
import matplotlib
import numpy as np


In [ ]:
print("Python",sys.version)
print("Matplotlib",matplotlib.__version__)
print("Numpy",np.__version__)

Python 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
Matplotlib 3.10.0
Numpy 2.0.2


In [ ]:
#we assume hypothetical 3 neurons feeding in as inputs
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1]#unique wt for each neuron##shifts magnitude,even can change to pos or neg
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.1,0.4,0.5,0.9]
bias1=2 #every neuron has one bias##shifts graph up or down(offsets the value)###without biases it would be a linear function
bias2=1
bias3=3
#taking weight as list of lists
#output=inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]
#print(output)

In [ ]:
!git config --global user.email "dhar.adhibhu@gmail.com"
!git config --global user.name "AdhibhuDhar"


In [ ]:
weights=[[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.1,0.4,0.5,0.9]]
biases=[2,1,3]

#zip combines two lists into list of lists element wise
layer_outputs=[]#op of current layer
for neuron_weights,neuron_bias in zip(weights,biases):
  neuron_output=0 #output of given neuron
  for n_input,weight in zip(inputs,neuron_weights):
    neuron_output+=n_input*weight
  neuron_output+=neuron_bias # Add bias once per neuron
  layer_outputs.append(neuron_output)
print(layer_outputs)


[4.8, -0.79, 7.45]


In [ ]:
#using dot prod
output=np.dot(weights,inputs)+biases #the first el we pass is how the return is to be indexed,like how do we know e had three neurons,yes,we had a LOL of 3 sets of weights
print(output)

[ 4.8  -0.79  7.45]


In [ ]:
weights=[[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.1,0.4,0.5,0.9]]#batches help in generalisation
biases=[2,1,3]
inputs=[[1,2,3,2.5],
        [2.0,1.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
# Transpose the weights to align dimensions for batch processing: (batch_size, num_features) @ (num_features, num_neurons)
#y=(w(T)x+bias)
weights2=[[0.1,-0.14,0.5],[-0.5,0.12,0.33],[-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]
layer1_output=np.dot(inputs,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2
print(layer2_output)

[[ 3.3156   1.9637  -4.1572 ]
 [ 1.8438   0.6146  -3.7171 ]
 [ 1.85386  2.88392 -2.48397]]


In [ ]:
X=[[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.1,0.4,0.5,0.9]]
np.random.seed(0)#start randomness from 0

class Layer_Dense: #without self its a memory game
  def __init__(self,n_inputs,n_neurons): #is the constructor method in Python, used to initialize a class instance's attributes automatically when an object is created. The __init__ (dunder init) method acts as a constructor, with self representing the specific object being created, allowing it to store data
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    #earlier it was weight by inputs,we did this inputs by weights to not do transpose again in forward pass
    #what is the size of inputs coming n,and how many neurons,#randn in gauss distb bounded around 0
    self.biases=np.zeros((1,n_neurons))#shape is 1  by however neurons we have,since we have a single bias for each neuron eg 3 neuron=[0,0,0],also the tuple of shape is a param
     #whatever code inside init automatically runs when obj is created
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)
layer1.forward(X) #layer1 op
print(layer1.output)
layer2.forward(layer1.output)#layer 1 op becomes layer 2 ip
print(layer2.output)


[[-0.01673593  0.16070445 -0.05110153  0.06178338 -0.0374037 ]
 [ 0.16419632 -0.10334303  0.0927553   0.10894774  0.11025867]
 [-0.01949877  0.24118276  0.00374597  0.00772216 -0.05692709]]
[[ 0.0011153  -0.01224121]
 [-0.01240057  0.01907355]
 [ 0.01798664 -0.0282282 ]]


In [ ]:
#Activation func
#H(x) takes input*weight+bias
#we can offset activation point by tweaking biases
#if we negate the weight,we can switch from saying where the input activates to deactivates
#slope gets steeper when we go on increasing weights

In [ ]:
#ReLU barebones
input=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]
for i in input:
  if i<=0:
    output.append(0)
  elif i>0:
    output.append(i)
#print(output)

#or

for i in input:
  output.append(max(0,i))
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0, 0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
#ReLU object
X=[[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.1,0.4,0.5,0.9]]
np.random.seed(0)#start randomness from 0

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)

    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)
class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs/np.max(inputs,axis=1,keepdims=True))
    probabilites=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilites



[[-0.01673593  0.16070445 -0.05110153  0.06178338 -0.0374037 ]
 [ 0.16419632 -0.10334303  0.0927553   0.10894774  0.11025867]
 [-0.01949877  0.24118276  0.00374597  0.00772216 -0.05692709]]
[[ 0.0011153  -0.01224121]
 [-0.01240057  0.01907355]
 [ 0.01798664 -0.0282282 ]]


In [ ]:
#softmax acitvation
#we use softmax to measure how wrong the model is by converting vec of real logits into a probability distb
#with just relu,neg values in op layer clips it to 0
#we exp to conv negative to positive without losing meaning
layer_outputs=[4.8,1.21,2.85]
import math
E=math.e
#print(E)
exp_values=[]
for output in layer_outputs:
  exp_values.append(E**output)
#print(exp_values)
norm_values=[]#normalising
for val in exp_values:
  norm_values.append(val/sum(exp_values))
#print(norm_values)
#print(sum(norm_values))

#using numpy
layer_outputs=[[4.8,1.21,2.385],[8.9,-1.81,0.2],[1.41,1.051,0.026]]
exp_values=np.exp(layer_outputs)
#norm_values=exp_values/np.sum(exp_values)
#print(norm_values)
#print(sum(norm_values))
#print(np.sum(layer_outputs,axis=1,keepdims=True))
norm_values=exp_values/np.sum(exp_values,axis=1,keepdims=True)
#print(norm_values)
#exp leads to overflow,hence v=u-max(u),so largest value for v is 0 and others is less than 0
new_layer=layer_outputs-np.max(layer_outputs,axis=1,keepdims=True)
print(new_layer)
exp_values=np.exp(new_layer)
norm_values=exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(norm_values)

[[  0.     -3.59   -2.415]
 [  0.    -10.71   -8.7  ]
 [  0.     -0.359  -1.384]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
